services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000/api
      - VITE_API_BASE_URL=http://backend:8000/api
      - VITE_AUTH_USERNAME=${VITE_AUTH_USERNAME}
      - VITE_AUTH_PASSWORD=${VITE_AUTH_PASSWORD}
      - REACT_APP_BACKEND_URL=http://backend:8000/api
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-defaultdb}
      - DB_PORT=${DB_PORT:-3306}
